services:
  spring-app:
    container_name: homelab-spring-app
    build:
      context: ./app
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./app/src:/app/src
      - ./app/pom.xml:/app/pom.xml
      - ./maven_cache:/root/.m2
      - ./ssh_credentials/hosting-portal-key:/app/ssh/hosting-portal-key:ro
      - ./ssh_credentials/known_hosts:/app/config/known_hosts:ro
    environment:
      - SSH_HOST=${SSH_HOST}
      - SSH_PORT=${SSH_PORT}
      - SSH_USERNAME=${SSH_USERNAME}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge